/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as RestablecerContrasenaRouteImport } from './routes/restablecer-contrasena'
import { Route as ResponsableLoginRouteImport } from './routes/responsable-login'
import { Route as ResponsableRouteImport } from './routes/responsable'
import { Route as RecuperarContrasenaRouteImport } from './routes/recuperar-contrasena'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VendedorSlugRouteImport } from './routes/vendedor.$slug'
import { Route as BonoCodigoRouteImport } from './routes/bono.$codigo'
import { Route as BoletaCodigoRouteImport } from './routes/boleta.$codigo'
import { Route as AdminSorteoRouteImport } from './routes/admin.sorteo'
import { Route as AdminRifaRouteImport } from './routes/admin.rifa'
import { Route as AdminResponsablesRouteImport } from './routes/admin.responsables'
import { Route as AdminRecordatoriosRouteImport } from './routes/admin.recordatorios'
import { Route as AdminPagosRouteImport } from './routes/admin.pagos'
import { Route as AdminPadrinosRouteImport } from './routes/admin.padrinos'
import { Route as AdminDistribucionRouteImport } from './routes/admin.distribucion'
import { Route as AdminBonosRouteImport } from './routes/admin.bonos'
import { Route as AdminAlquileresRouteImport } from './routes/admin.alquileres'
import { Route as AdminBonosRaffleIdRouteImport } from './routes/admin.bonos.$raffleId'

const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const RestablecerContrasenaRoute = RestablecerContrasenaRouteImport.update({
  id: '/restablecer-contrasena',
  path: '/restablecer-contrasena',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsableLoginRoute = ResponsableLoginRouteImport.update({
  id: '/responsable-login',
  path: '/responsable-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsableRoute = ResponsableRouteImport.update({
  id: '/responsable',
  path: '/responsable',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarContrasenaRoute = RecuperarContrasenaRouteImport.update({
  id: '/recuperar-contrasena',
  path: '/recuperar-contrasena',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VendedorSlugRoute = VendedorSlugRouteImport.update({
  id: '/vendedor/$slug',
  path: '/vendedor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BonoCodigoRoute = BonoCodigoRouteImport.update({
  id: '/bono/$codigo',
  path: '/bono/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const BoletaCodigoRoute = BoletaCodigoRouteImport.update({
  id: '/boleta/$codigo',
  path: '/boleta/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSorteoRoute = AdminSorteoRouteImport.update({
  id: '/sorteo',
  path: '/sorteo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRifaRoute = AdminRifaRouteImport.update({
  id: '/rifa',
  path: '/rifa',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResponsablesRoute = AdminResponsablesRouteImport.update({
  id: '/responsables',
  path: '/responsables',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecordatoriosRoute = AdminRecordatoriosRouteImport.update({
  id: '/recordatorios',
  path: '/recordatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagosRoute = AdminPagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPadrinosRoute = AdminPadrinosRouteImport.update({
  id: '/padrinos',
  path: '/padrinos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDistribucionRoute = AdminDistribucionRouteImport.update({
  id: '/distribucion',
  path: '/distribucion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBonosRoute = AdminBonosRouteImport.update({
  id: '/bonos',
  path: '/bonos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlquileresRoute = AdminAlquileresRouteImport.update({
  id: '/alquileres',
  path: '/alquileres',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBonosRaffleIdRoute = AdminBonosRaffleIdRouteImport.update({
  id: '/$raffleId',
  path: '/$raffleId',
  getParentRoute: () => AdminBonosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/recuperar-contrasena': typeof RecuperarContrasenaRoute
  '/responsable': typeof ResponsableRoute
  '/responsable-login': typeof ResponsableLoginRoute
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/resultados': typeof ResultadosRoute
  '/admin/alquileres': typeof AdminAlquileresRoute
  '/admin/bonos': typeof AdminBonosRouteWithChildren
  '/admin/distribucion': typeof AdminDistribucionRoute
  '/admin/padrinos': typeof AdminPadrinosRoute
  '/admin/pagos': typeof AdminPagosRoute
  '/admin/recordatorios': typeof AdminRecordatoriosRoute
  '/admin/responsables': typeof AdminResponsablesRoute
  '/admin/rifa': typeof AdminRifaRoute
  '/admin/sorteo': typeof AdminSorteoRoute
  '/boleta/$codigo': typeof BoletaCodigoRoute
  '/bono/$codigo': typeof BonoCodigoRoute
  '/vendedor/$slug': typeof VendedorSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/bonos/$raffleId': typeof AdminBonosRaffleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/recuperar-contrasena': typeof RecuperarContrasenaRoute
  '/responsable': typeof ResponsableRoute
  '/responsable-login': typeof ResponsableLoginRoute
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/resultados': typeof ResultadosRoute
  '/admin/alquileres': typeof AdminAlquileresRoute
  '/admin/bonos': typeof AdminBonosRouteWithChildren
  '/admin/distribucion': typeof AdminDistribucionRoute
  '/admin/padrinos': typeof AdminPadrinosRoute
  '/admin/pagos': typeof AdminPagosRoute
  '/admin/recordatorios': typeof AdminRecordatoriosRoute
  '/admin/responsables': typeof AdminResponsablesRoute
  '/admin/rifa': typeof AdminRifaRoute
  '/admin/sorteo': typeof AdminSorteoRoute
  '/boleta/$codigo': typeof BoletaCodigoRoute
  '/bono/$codigo': typeof BonoCodigoRoute
  '/vendedor/$slug': typeof VendedorSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/bonos/$raffleId': typeof AdminBonosRaffleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/recuperar-contrasena': typeof RecuperarContrasenaRoute
  '/responsable': typeof ResponsableRoute
  '/responsable-login': typeof ResponsableLoginRoute
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/resultados': typeof ResultadosRoute
  '/admin/alquileres': typeof AdminAlquileresRoute
  '/admin/bonos': typeof AdminBonosRouteWithChildren
  '/admin/distribucion': typeof AdminDistribucionRoute
  '/admin/padrinos': typeof AdminPadrinosRoute
  '/admin/pagos': typeof AdminPagosRoute
  '/admin/recordatorios': typeof AdminRecordatoriosRoute
  '/admin/responsables': typeof AdminResponsablesRoute
  '/admin/rifa': typeof AdminRifaRoute
  '/admin/sorteo': typeof AdminSorteoRoute
  '/boleta/$codigo': typeof BoletaCodigoRoute
  '/bono/$codigo': typeof BonoCodigoRoute
  '/vendedor/$slug': typeof VendedorSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/bonos/$raffleId': typeof AdminBonosRaffleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/admin'
    | '/auth'
    | '/recuperar-contrasena'
    | '/responsable'
    | '/responsable-login'
    | '/restablecer-contrasena'
    | '/resultados'
    | '/admin/alquileres'
    | '/admin/bonos'
    | '/admin/distribucion'
    | '/admin/padrinos'
    | '/admin/pagos'
    | '/admin/recordatorios'
    | '/admin/responsables'
    | '/admin/rifa'
    | '/admin/sorteo'
    | '/boleta/$codigo'
    | '/bono/$codigo'
    | '/vendedor/$slug'
    | '/admin/'
    | '/admin/bonos/$raffleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/auth'
    | '/recuperar-contrasena'
    | '/responsable'
    | '/responsable-login'
    | '/restablecer-contrasena'
    | '/resultados'
    | '/admin/alquileres'
    | '/admin/bonos'
    | '/admin/distribucion'
    | '/admin/padrinos'
    | '/admin/pagos'
    | '/admin/recordatorios'
    | '/admin/responsables'
    | '/admin/rifa'
    | '/admin/sorteo'
    | '/boleta/$codigo'
    | '/bono/$codigo'
    | '/vendedor/$slug'
    | '/admin'
    | '/admin/bonos/$raffleId'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/admin'
    | '/auth'
    | '/recuperar-contrasena'
    | '/responsable'
    | '/responsable-login'
    | '/restablecer-contrasena'
    | '/resultados'
    | '/admin/alquileres'
    | '/admin/bonos'
    | '/admin/distribucion'
    | '/admin/padrinos'
    | '/admin/pagos'
    | '/admin/recordatorios'
    | '/admin/responsables'
    | '/admin/rifa'
    | '/admin/sorteo'
    | '/boleta/$codigo'
    | '/bono/$codigo'
    | '/vendedor/$slug'
    | '/admin/'
    | '/admin/bonos/$raffleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  RecuperarContrasenaRoute: typeof RecuperarContrasenaRoute
  ResponsableRoute: typeof ResponsableRoute
  ResponsableLoginRoute: typeof ResponsableLoginRoute
  RestablecerContrasenaRoute: typeof RestablecerContrasenaRoute
  ResultadosRoute: typeof ResultadosRoute
  BoletaCodigoRoute: typeof BoletaCodigoRoute
  BonoCodigoRoute: typeof BonoCodigoRoute
  VendedorSlugRoute: typeof VendedorSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restablecer-contrasena': {
      id: '/restablecer-contrasena'
      path: '/restablecer-contrasena'
      fullPath: '/restablecer-contrasena'
      preLoaderRoute: typeof RestablecerContrasenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsable-login': {
      id: '/responsable-login'
      path: '/responsable-login'
      fullPath: '/responsable-login'
      preLoaderRoute: typeof ResponsableLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsable': {
      id: '/responsable'
      path: '/responsable'
      fullPath: '/responsable'
      preLoaderRoute: typeof ResponsableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-contrasena': {
      id: '/recuperar-contrasena'
      path: '/recuperar-contrasena'
      fullPath: '/recuperar-contrasena'
      preLoaderRoute: typeof RecuperarContrasenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vendedor/$slug': {
      id: '/vendedor/$slug'
      path: '/vendedor/$slug'
      fullPath: '/vendedor/$slug'
      preLoaderRoute: typeof VendedorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bono/$codigo': {
      id: '/bono/$codigo'
      path: '/bono/$codigo'
      fullPath: '/bono/$codigo'
      preLoaderRoute: typeof BonoCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boleta/$codigo': {
      id: '/boleta/$codigo'
      path: '/boleta/$codigo'
      fullPath: '/boleta/$codigo'
      preLoaderRoute: typeof BoletaCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sorteo': {
      id: '/admin/sorteo'
      path: '/sorteo'
      fullPath: '/admin/sorteo'
      preLoaderRoute: typeof AdminSorteoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rifa': {
      id: '/admin/rifa'
      path: '/rifa'
      fullPath: '/admin/rifa'
      preLoaderRoute: typeof AdminRifaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/responsables': {
      id: '/admin/responsables'
      path: '/responsables'
      fullPath: '/admin/responsables'
      preLoaderRoute: typeof AdminResponsablesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recordatorios': {
      id: '/admin/recordatorios'
      path: '/recordatorios'
      fullPath: '/admin/recordatorios'
      preLoaderRoute: typeof AdminRecordatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagos': {
      id: '/admin/pagos'
      path: '/pagos'
      fullPath: '/admin/pagos'
      preLoaderRoute: typeof AdminPagosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/padrinos': {
      id: '/admin/padrinos'
      path: '/padrinos'
      fullPath: '/admin/padrinos'
      preLoaderRoute: typeof AdminPadrinosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/distribucion': {
      id: '/admin/distribucion'
      path: '/distribucion'
      fullPath: '/admin/distribucion'
      preLoaderRoute: typeof AdminDistribucionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bonos': {
      id: '/admin/bonos'
      path: '/bonos'
      fullPath: '/admin/bonos'
      preLoaderRoute: typeof AdminBonosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alquileres': {
      id: '/admin/alquileres'
      path: '/alquileres'
      fullPath: '/admin/alquileres'
      preLoaderRoute: typeof AdminAlquileresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bonos/$raffleId': {
      id: '/admin/bonos/$raffleId'
      path: '/$raffleId'
      fullPath: '/admin/bonos/$raffleId'
      preLoaderRoute: typeof AdminBonosRaffleIdRouteImport
      parentRoute: typeof AdminBonosRoute
    }
  }
}

interface AdminBonosRouteChildren {
  AdminBonosRaffleIdRoute: typeof AdminBonosRaffleIdRoute
}

const AdminBonosRouteChildren: AdminBonosRouteChildren = {
  AdminBonosRaffleIdRoute: AdminBonosRaffleIdRoute,
}

const AdminBonosRouteWithChildren = AdminBonosRoute._addFileChildren(
  AdminBonosRouteChildren,
)

interface AdminRouteChildren {
  AdminAlquileresRoute: typeof AdminAlquileresRoute
  AdminBonosRoute: typeof AdminBonosRouteWithChildren
  AdminDistribucionRoute: typeof AdminDistribucionRoute
  AdminPadrinosRoute: typeof AdminPadrinosRoute
  AdminPagosRoute: typeof AdminPagosRoute
  AdminRecordatoriosRoute: typeof AdminRecordatoriosRoute
  AdminResponsablesRoute: typeof AdminResponsablesRoute
  AdminRifaRoute: typeof AdminRifaRoute
  AdminSorteoRoute: typeof AdminSorteoRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlquileresRoute: AdminAlquileresRoute,
  AdminBonosRoute: AdminBonosRouteWithChildren,
  AdminDistribucionRoute: AdminDistribucionRoute,
  AdminPadrinosRoute: AdminPadrinosRoute,
  AdminPagosRoute: AdminPagosRoute,
  AdminRecordatoriosRoute: AdminRecordatoriosRoute,
  AdminResponsablesRoute: AdminResponsablesRoute,
  AdminRifaRoute: AdminRifaRoute,
  AdminSorteoRoute: AdminSorteoRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  RecuperarContrasenaRoute: RecuperarContrasenaRoute,
  ResponsableRoute: ResponsableRoute,
  ResponsableLoginRoute: ResponsableLoginRoute,
  RestablecerContrasenaRoute: RestablecerContrasenaRoute,
  ResultadosRoute: ResultadosRoute,
  BoletaCodigoRoute: BoletaCodigoRoute,
  BonoCodigoRoute: BonoCodigoRoute,
  VendedorSlugRoute: VendedorSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
