/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as BoletaCodigoRouteImport } from './routes/boleta.$codigo'
import { Route as AdminSorteoRouteImport } from './routes/admin.sorteo'
import { Route as AdminRifaRouteImport } from './routes/admin.rifa'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const BoletaCodigoRoute = BoletaCodigoRouteImport.update({
  id: '/boleta/$codigo',
  path: '/boleta/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSorteoRoute = AdminSorteoRouteImport.update({
  id: '/sorteo',
  path: '/sorteo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRifaRoute = AdminRifaRouteImport.update({
  id: '/rifa',
  path: '/rifa',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/rifa': typeof AdminRifaRoute
  '/admin/sorteo': typeof AdminSorteoRoute
  '/boleta/$codigo': typeof BoletaCodigoRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/rifa': typeof AdminRifaRoute
  '/admin/sorteo': typeof AdminSorteoRoute
  '/boleta/$codigo': typeof BoletaCodigoRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/rifa': typeof AdminRifaRoute
  '/admin/sorteo': typeof AdminSorteoRoute
  '/boleta/$codigo': typeof BoletaCodigoRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/rifa'
    | '/admin/sorteo'
    | '/boleta/$codigo'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/rifa'
    | '/admin/sorteo'
    | '/boleta/$codigo'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/rifa'
    | '/admin/sorteo'
    | '/boleta/$codigo'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BoletaCodigoRoute: typeof BoletaCodigoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/boleta/$codigo': {
      id: '/boleta/$codigo'
      path: '/boleta/$codigo'
      fullPath: '/boleta/$codigo'
      preLoaderRoute: typeof BoletaCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sorteo': {
      id: '/admin/sorteo'
      path: '/sorteo'
      fullPath: '/admin/sorteo'
      preLoaderRoute: typeof AdminSorteoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rifa': {
      id: '/admin/rifa'
      path: '/rifa'
      fullPath: '/admin/rifa'
      preLoaderRoute: typeof AdminRifaRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminRifaRoute: typeof AdminRifaRoute
  AdminSorteoRoute: typeof AdminSorteoRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminRifaRoute: AdminRifaRoute,
  AdminSorteoRoute: AdminSorteoRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BoletaCodigoRoute: BoletaCodigoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
